### PR TITLE
Added support for rspec alias and add feature spec

### LINKED ISSUE #18: Support all aliased RSpec expectations
[RSpec expectation is supported](https://www.relishapp.com/waterlink/rspec-json-expectations/docs/json-expectations/rspec-matcher-support-for-include-json-matcher), but not all their aliases:

``` ruby
require 'rspec/json_expectations'

describe 'sample' do
  it 'passes with original matcher' do
    json = '{"foo":"bar"}'
    expect(json).to include_json(
      foo: be_a_kind_of(String)
    )
  end

  it 'should have succeeded' do
    expect('bar').to a_kind_of(String)
  end

  it 'fails' do
    json = '{"foo":"bar"}'
    expect(json).to include_json(
      foo: a_kind_of(String)
    )
  end
end
```

Here `a_kind_of` is an alias of [`be_a_kind_of`](http://www.rubydoc.info/gems/rspec-expectations/RSpec/Matchers#be_a_kind_of-instance_method). I find the noun-phrase aliases fit better here. Notably `be_kind_of`, another alias of `be_a_kind_of`, is supported. Any reason to reject the noun-phrase?

### PR DESCRIPTION
**Pull request by JanStevens**
Fixes #18

### CODE REVIEW

**Comment by JanStevens** [comment]
Fails since rspec 2 does not have `RSpec::Matchers::AliasedMatcher`

**Comment by waterlink** [comment]
I feel like it is not necessary to drop RSpec2 support. One could disable the feature test for Rspec2 and also conditionally use or not use `AliasedMatcher`.

**Comment by waterlink** [comment]
While it is not necessary, I think it would be a good thing :)

**Comment by JanStevens** [comment]
So another MR for removing rspec 2 support?

**Comment by waterlink** [comment]
@JanStevens Yes

**Comment by waterlink** [comment]
@JanStevens I have merged the other PR. And now this has conflicts, could you please resolve them?

**Comment by waterlink** [comment]
@JanStevens Thank you! And I have released this as `2.1.0` to rubygems.

**Pull request merged**
