### PR TITLE
Fixes TypeError where values can't be implictly converted to string.

### PR DESCRIPTION
**Pull request by shamil614**

### CODE REVIEW

**Comment by shamil614** [comment]
Made this change because I couldn't use regexes on Boolean, null, and numbers. Not sure why the build is failing. Looks like it's failing on installing dependencies.

**Comment by waterlink** [comment]
@shamil614 Thanks! Let me take a look.

**Comment by waterlink** [comment]
I see. Outdated version of `bundler` (no longer compatible with current `rubygems` gem). Will fix shortly.

**Comment by waterlink** [comment]
@shamil614 I have fixed the issue with build and merged fix to the `master` branch. Could you please rebase your branch on the top of `master` branch?

**Comment by shamil614** [comment]
you bet. looks like that did it. let me know if i need to make any other changes. just wanting to help. Thanks for the awesome work on this gem!

**Comment by waterlink** [comment]
LGTM

**Comment by waterlink** [comment]
I have released `1.2.1` version

**Pull request merged**
